server:
  port: 8090
spring:
  application:
    name: manager
  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: bruce
    password: 123456
mybatis:
  type-aliases-package: com.bruce.manager.model  # 注意：对应实体类的路径
  mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径